// The verifier — the one command a judge runs.
//
//   pnpm verify
//
// It reads results/receipts.jsonl and re-derives every claim from a PUBLIC RPC,
// independently of the indexer that wrote the file. It never trusts the file: if
// a row says an order was placed, this fetches that transaction and checks the
// agent really sent it and the decoded arguments really match.
//
// Exits non-zero on any mismatch. Also writes results/RESULTS.md so the published
// numbers and the verification are generated by the same pass — a number in
// RESULTS.md that this script cannot re-derive cannot exist.
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { decodeEventLog } from "viem";
import { pub, done } from "./config.js";
import { traderAbi } from "./contracts.js";

import { RESULTS as RESULTS_DIR, join } from "./paths.js";
const RESULTS = RESULTS_DIR();
const FILE = join(RESULTS, "receipts.jsonl");

if (!existsSync(FILE)) {
  console.error("results/receipts.jsonl not found — run `pnpm index` first.");
  done(1);
}

const rows = readFileSync(FILE, "utf8")
  .split("\n")
  .filter(Boolean)
  .map((l) => JSON.parse(l));

console.log(`verifying ${rows.length} row(s) against ${pub.transport.url ?? "the public RPC"}\n`);

let verified = 0;
let failures = 0;
const fail = (row: any, msg: string) => {
  failures++;
  console.log(`  FAIL ${row.agent?.slice(0, 10)}… req ${row.requestId}: ${msg}`);
};

/** Pull the decoded agent events out of a transaction, straight from the chain. */
async function eventsOf(txHash: `0x${string}`, agent: string) {
  const receipt = await pub.getTransactionReceipt({ hash: txHash });
  const out: { name: string; args: any }[] = [];
  for (const l of receipt.logs) {
    if (l.address.toLowerCase() !== agent.toLowerCase()) continue;
    try {
      const ev = decodeEventLog({ abi: traderAbi, data: l.data, topics: l.topics });
      out.push({ name: ev.eventName as string, args: ev.args as any });
    } catch {
      /* not one of ours */
    }
  }
  return { receipt, events: out };
}

const latencies: number[] = [];

for (const row of rows) {
  let rowOk = true;

  // 1. The decision was opened by the agent contract itself.
  if (row.openedTx) {
    try {
      const { events } = await eventsOf(row.openedTx, row.agent);
      const opened = events.find((e) => e.name === "WindowOpened");
      if (!opened) {
        fail(row, "openedTx emitted no WindowOpened from this agent");
        rowOk = false;
      } else if (String(opened.args.requestId) !== String(row.requestId)) {
        fail(row, `requestId mismatch: chain=${opened.args.requestId} file=${row.requestId}`);
        rowOk = false;
      } else if (opened.args.marketId !== row.marketId) {
        fail(row, "marketId mismatch against chain");
        rowOk = false;
      }
    } catch (err: any) {
      fail(row, `openedTx unreadable: ${String(err?.message ?? err).slice(0, 80)}`);
      rowOk = false;
    }
  }

  // 2. If an order was published, the agent really sent it with those arguments.
  if (row.orderTx) {
    try {
      const { receipt, events } = await eventsOf(row.orderTx, row.agent);
      const placed = events.find((e) => e.name === "OrderPlaced");
      if (!placed) {
        fail(row, "orderTx emitted no OrderPlaced from this agent");
        rowOk = false;
      } else {
        if (String(placed.args.price) !== String(row.orderPrice)) {
          fail(row, `price mismatch: chain=${placed.args.price} file=${row.orderPrice}`);
          rowOk = false;
        }
        if (String(placed.args.quantity) !== String(row.orderQty)) {
          fail(row, `quantity mismatch: chain=${placed.args.quantity} file=${row.orderQty}`);
          rowOk = false;
        }
        if (Number(placed.args.kind) !== Number(row.orderKind)) {
          fail(row, `order kind mismatch`);
          rowOk = false;
        }
      }
      if (receipt.status !== "success") {
        fail(row, "orderTx did not succeed on chain");
        rowOk = false;
      }
    } catch (err: any) {
      fail(row, `orderTx unreadable: ${String(err?.message ?? err).slice(0, 80)}`);
      rowOk = false;
    }
  }

  // 3. A row claiming a gate PASS must carry an order, and a rejection must not.
  if (row.gateReason === 0 && row.verdict !== 0 && !row.orderTx && row.filled) {
    fail(row, "claims a filled order but has no orderTx");
    rowOk = false;
  }
  if (row.gateReason !== undefined && row.gateReason !== 0 && row.orderTx) {
    fail(row, "claims a gate rejection but also an order");
    rowOk = false;
  }

  // 4. Consensus claims must not exceed the subcommittee that actually ran.
  if (row.agreeing !== undefined && row.subcommittee !== undefined) {
    if (row.agreeing > row.subcommittee) {
      fail(row, `more agreeing (${row.agreeing}) than subcommittee members (${row.subcommittee})`);
      rowOk = false;
    }
  }

  // 5. Latency, measured from block timestamps rather than asserted.
  if (row.openedTx && row.orderTx && row.openedTx !== row.orderTx) {
    try {
      const [a, b] = await Promise.all([
        pub.getTransactionReceipt({ hash: row.openedTx }),
        pub.getTransactionReceipt({ hash: row.orderTx }),
      ]);
      const [ba, bb] = await Promise.all([
        pub.getBlock({ blockNumber: a.blockNumber }),
        pub.getBlock({ blockNumber: b.blockNumber }),
      ]);
      const dt = Number(bb.timestamp - ba.timestamp);
      if (dt >= 0) latencies.push(dt);
    } catch {
      /* latency is best-effort */
    }
  }

  if (rowOk) verified++;
}

// ------------------------------------------------------------------ summary

const pct = (arr: number[], p: number) => {
  if (arr.length === 0) return null;
  const s = [...arr].sort((a, b) => a - b);
  return s[Math.min(s.length - 1, Math.floor((p / 100) * s.length))];
};

const withVerdict = rows.filter((r) => r.verdict !== undefined);
const unanimous = withVerdict.filter((r) => r.agreeing === r.subcommittee).length;
const rejected = rows.filter((r) => r.gateReason !== undefined && r.gateReason !== 0);
const placed = rows.filter((r) => r.orderTx).length;
const expired = rows.filter((r) => r.expired).length;
const failedReq = rows.filter((r) => r.requestStatus !== undefined).length;
const agentsSeen = new Set(rows.map((r) => String(r.agent).toLowerCase()));

const byReason = new Map<string, number>();
for (const r of rejected) byReason.set(r.gateLabel, (byReason.get(r.gateLabel) ?? 0) + 1);

console.log(`
verified   ${verified} / ${rows.length}
failed     ${failures}`);

const md = `# RESULTS

Generated by \`pnpm verify\` on ${new Date().toISOString()}.
Every number below is re-derived from a public Somnia Shannon RPC by that same
command. Nothing here is asserted by hand — run it yourself:

\`\`\`bash
pnpm install && pnpm build:contracts && pnpm index && pnpm verify
\`\`\`

## Verification

| | |
|---|---|
| rows verified | ${verified} / ${rows.length} |
| verification failures | ${failures} |

## Decisions

| | |
|---|---|
| agents observed | ${agentsSeen.size} |
| decisions (inference requests) | ${rows.length} |
| verdicts returned | ${withVerdict.length} |
| full-subcommittee agreement | ${unanimous} of ${withVerdict.length} |
| orders placed on DreamDEX | ${placed} |
| gate rejections | ${rejected.length} |
| requests failed | ${failedReq} |
| requests expired | ${expired} |

## Risk-gate rejections by rule

The gate is pure Solidity and no model output can change its bounds. Rejections
are published, not hidden — a gate that never rejects is a gate nobody can trust.

${
  byReason.size
    ? "| rule | count |\n|---|---|\n" +
      [...byReason].sort((a, b) => b[1] - a[1]).map(([r, n]) => `| ${r} | ${n} |`).join("\n")
    : "_No rejections recorded yet._"
}

## Latency (request open → order, from block timestamps)

| | |
|---|---|
| samples | ${latencies.length} |
| median | ${pct(latencies, 50) ?? "n/a"}s |
| p95 | ${pct(latencies, 95) ?? "n/a"}s |

## Transactions

${
  rows.filter((r) => r.orderTx).length
    ? rows
        .filter((r) => r.orderTx)
        .map((r) => `- \`${r.orderTx}\` — ${r.agentName ?? r.agent} · ${r.verdictLabel}`)
        .join("\n")
    : "_No orders placed yet._"
}
`;

mkdirSync(RESULTS, { recursive: true });
writeFileSync(join(RESULTS, "RESULTS.md"), md);
console.log("\nwrote results/RESULTS.md");

done(failures === 0 ? 0 : 1);
